apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    avp.kubernetes.io/path: "credentials/data/github"
stringData:
  type: git
  url: https://github.com/trucdp/argocd-example-apps-private.git
  githubAppID: 1
  githubAppInstallationID: 2
  githubAppPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
     # key goes here  NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops.
    -----END OPENSSH PRIVATE KEY-----
